services:
  base:
    entrypoint:
    - sleep
    - infinity
    image: kindtek/dbp:base
    build:
      context: .
      target: dbp_base
    platform: linux/amd64
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

  git:
    entrypoint:
    - sleep
    - infinity
    image: kindtek/dbp:git
    build:
      context: .
      target: dbp_git
    platform: linux/amd64
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      
  docker-git:
    entrypoint:
    - sleep
    - infinity
    image: kindtek/dbp:docker-git
    build:
      context: .
      target: dbp_docker-git
    platform: linux/amd64
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

