services:
  essential:
    entrypoint:
    - sleep
    - infinity
    image: kindtek/dbp-essential
    build:
      context: .
      target: dbp-essential
    platform: linux/amd64
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
  git:
    entrypoint:
    - sleep
    - infinity
    image: kindtek/dbp-git
    build:
      context: .
      target: dbp-git
    platform: linux/amd64
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
  docker-git:
    entrypoint:
    - sleep
    - infinity
    image: kindtek/dbp-docker-git
    build:
      context: .
      target: dbp-docker-git
    platform: linux/amd64
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

