services:
  essential-cdir:
    entrypoint:
    - sleep
    - infinity
    image: kindtek/dbp-essential-cdir
    build:
      context: .
      target: dbp-essential-cdir
    platform: linux/amd64
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
  git-cdir:
    entrypoint:
    - sleep
    - infinity
    image: kindtek/dbp-git-cdir
    build:
      context: .
      target: dbp-git-cdir
    platform: linux/amd64
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
  docker-git-cdir:
    entrypoint:
    - sleep
    - infinity
    image: kindtek/dbp-docker-git-cdir
    build:
      context: .
      target: dbp-docker-git-cdir
    platform: linux/amd64
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

