services:
  essential-cdir:
    entrypoint:
    - sleep
    - infinity
    # command: /bin/bash echo "alias cdir='source cdir.sh'" >> ~/.bashrc && source ~/.bashrc
    image: kindtek/dbp_essential-cdir
    build:
      context: .
      target: dbp_essential-cdir
    platform: linux/amd64
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

  git-cdir:
    entrypoint:
    - sleep
    - infinity
    image: kindtek/dbp_git-cdir
    build:
      context: .
      target: dbp_git-cdir
    platform: linux/amd64
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      
  docker-git-cdir:
    entrypoint:
    - sleep
    - infinity
    image: kindtek/dbp_docker-git-cdir
    build:
      context: .
      target: dbp_docker-git-cdir
    platform: linux/amd64
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

